BEGIN TRANSACTION;
CREATE TABLE Rank(id INTEGER PRIMARY KEY, name TEXT NOT NULL, points INTEGER NOT NULL);
CREATE TABLE Save(id INTEGER PRIMARY KEY, sudoku TEXT NOT NULL, time INTEGER NOT NULL, sudokuInit TEXT NOT NULL, dif INTEGER NOT NULL);
COMMIT;
