BEGIN TRANSACTION;
CREATE TABLE Rank(id INTEGER PRIMARY KEY, name TEXT NOT NULL, points INTEGER NOT NULL);
CREATE TABLE Save (resuelto TEXT, dif TEXT, semilla TEXT, id INTEGER PRIMARY KEY, sudokuActual TEXT, time INTEGER);
COMMIT;
